/*
Power Query Function: fnGetDeliveryDates
DESCRIPTION: Generates a list of delivery dates from the report's start year up to the year after today based on structured scheduling metadata (frequency + free-text delivery rules).
PARAMETERS:
frequency (text): Type of recurrence (e.g., "Monthly", "Quarterly", etc.)
startDate (date): First effective reporting date
deliveryText (nullable text): Raw delivery schedule description (e.g. "15 Working Day", "Tuesday and Friday")
calendar (table): A working day calendar table with the following columns:
Date (date)
IsWorkingDay (logical)
WeekdayName (text, e.g., "Monday")
RETURNS:
List of delivery dates (list of date) */
(frequency as text, startDate as date, deliveryText as nullable text, calendar as table) as list => let years = { Date.Year(startDate) .. Date.Year(DateTime.LocalNow()) + 1 },
// === Helper Functions ===

GetWorkingDays = (year, month) =>
    Table.SelectRows(calendar, each Date.Year([Date]) = year and Date.Month([Date]) = month and Record.FieldOrDefault(_, "IsWorkingDay", false) = true),

GetNthWorkingDay = (year, month, n) =>
    let wd = GetWorkingDays(year, month) in try wd{n - 1}[Date] otherwise null,

GetNthCalendarDay = (year, month, n) =>
    let base = try #date(year, month, n) otherwise null in
    if base <> null and Record.FieldOrDefault(Table.SelectRows(calendar, each [Date] = base){0}?, "IsWorkingDay", false) = false then
        try Table.SelectRows(calendar, each [Date] > base and [IsWorkingDay]){0}[Date] otherwise null
    else base,

GetLastWorkingDay = (year, month) =>
    let wd = GetWorkingDays(year, month) in try List.Last(wd[Date]) otherwise null,

GetNthFriday = (year, month, n) =>
    let
        fridays = Table.SelectRows(calendar, each Date.Year([Date]) = year and Date.Month([Date]) = month and [WeekdayName] = "Friday"),
        result = try fridays{n - 1}[Date] otherwise null
    in result,

FromEndOfMonth = (year, month, offsetWDays) =>
    let
        base = #date(year, month, Date.DaysInMonth(#date(year, month, 1))),
        wd = Table.SelectRows(calendar, each [Date] > base and [IsWorkingDay]),
        result = try wd{offsetWDays - 1}[Date] otherwise null
    in result,

FromEndOfQuarter = (year, quarterMonth, offsetMonths, offsetWDays) =>
    let
        base = #date(year, quarterMonth, Date.DaysInMonth(#date(year, quarterMonth, 1))),
        shifted = Date.AddMonths(base, offsetMonths),
        wd = Table.SelectRows(calendar, each [Date] > shifted and [IsWorkingDay]),
        result = try wd{offsetWDays - 1}[Date] otherwise null
    in result,

// === Frequency Logic ===

ExtractLeadingNumber = (txt as text) as nullable number =>
    let match = Text.Select(txt, {"0".."9"}) in try Number.FromText(match) otherwise null,

ExtractMultipleNumbers = (txt as text) as list =>
    let
        matches = Text.RegexReplace(txt, "[^0-9+]+", ","),
        numbers = List.Transform(List.Select(Text.Split(matches, ","), each _ <> ""), each try Number.FromText(_) otherwise null)
    in List.RemoveNulls(numbers),

HandleMonthly = List.Combine(List.Transform(years, each
    let y = _,
        months = List.Transform({1..12}, each
            if deliveryText <> null and Text.Contains(Text.Lower(deliveryText), "calendar") then
                GetNthCalendarDay(y, _, ExtractLeadingNumber(deliveryText))
            else if deliveryText <> null and Text.Contains(Text.Lower(deliveryText), "working") then
                if Text.Contains(Text.Lower(deliveryText), "end of month") then
                    let offset = ExtractLeadingNumber(deliveryText) in FromEndOfMonth(y, _, offset)
                else GetNthWorkingDay(y, _, ExtractLeadingNumber(deliveryText))
            else null)
    in List.RemoveNulls(months))
),

HandleDaily = Table.SelectRows(calendar, each [Date] >= startDate and [IsWorkingDay])[Date],

HandleWeekly = 
    if deliveryText <> null then
        let
            lowerText = Text.Lower(deliveryText),
            dayList = List.Select({"Monday", "Tuesday", "Wednesday", "Thursday", "Friday"}, each Text.Contains(lowerText, Text.Start(_, 3))),
            dates = Table.SelectRows(calendar, each [Date] >= startDate and List.Contains(dayList, [WeekdayName]))[Date]
        in dates
    else
        {},

HandleAnnually = List.Transform(years, each
    if deliveryText <> null and Text.Contains(Text.Lower(deliveryText), "march") then GetNthWorkingDay(_, 3, 15)
    else if deliveryText <> null and Text.Contains(Text.Lower(deliveryText), "january") then GetNthWorkingDay(_, 1, 15)
    else null
),

HandleBiAnnually = List.Combine(List.Transform(years, each
    let 
        periodList = Text.Split(Text.Lower(Text.Replace(Text.Replace(deliveryText, "&", ","), " and ", ",")), ","),
        parsed = List.Transform(List.RemoveNulls(periodList), each 
            if Text.Contains(_, "october") then GetNthWorkingDay(_, 10, 15)
            else if Text.Contains(_, "january") then GetNthWorkingDay(_, 1, 15)
            else if Text.Contains(_, "march") then GetNthWorkingDay(_, 3, 15)
            else null)
    in List.RemoveNulls(parsed)
)),

HandleQuarterly = List.Combine(List.Transform(years, each 
    let y = _,
        lower = Text.Lower(deliveryText),
        offset = ExtractLeadingNumber(lower),
        numbers = ExtractMultipleNumbers(lower),
        baseMonths = {3, 6, 9, 12},
        result =
            if Text.Contains(lower, "end of quarter") and Text.Contains(lower, "and") then
                List.RemoveNulls(List.Combine(List.Transform(baseMonths, each FromEndOfQuarter(y, _, 1, offset))))
            else if Text.Contains(lower, "end of quarter") then
                List.RemoveNulls(List.Transform(baseMonths, each FromEndOfQuarter(y, _, 1, offset)))
            else if Text.Contains(lower, "+") and List.Count(numbers) = 2 then
                List.RemoveNulls(List.Transform(baseMonths, each GetNthWorkingDay(y, _, if _ = 3 or _ = 9 then numbers{0} else numbers{1})))
            else if Text.Contains(lower, "week") then
                let
                    weekIndex = if Text.Contains(lower, "2nd") then 2 else if Text.Contains(lower, "3rd") then 3 else null
                in if weekIndex <> null then List.RemoveNulls(List.Transform(baseMonths, each GetNthFriday(y, _, weekIndex))) else {}
            else if Text.Contains(lower, "working") then
                List.RemoveNulls(List.Transform(baseMonths, each GetNthWorkingDay(y, _, offset)))
            else {}
    in result)
),

Result =
    if frequency = "Daily" then HandleDaily
    else if frequency = "Weekly" then HandleWeekly
    else if frequency = "Monthly" then HandleMonthly
    else if frequency = "Annually" then HandleAnnually
    else if frequency = "Bi-Annually" then HandleBiAnnually
    else if frequency = "Quarterly" then HandleQuarterly
    else if frequency = "On Demand" then {} // Treat as no recurrence
    else {}

in List.Distinct(List.RemoveNulls(Result))
